import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@repo/ui";
import DeskstopNavigationMenu from "@/components/layout/navbar/DeskstopNavigationMenu";
import Footer from "@/components/layout/footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "../../i18n/routing";

export const metadata: Metadata = {
  title: "Staff Outsourcing",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Your Company Name", // TODO: replace with actual company name
  url: "https://www.yoursite.com", // TODO: replace with actual domain
  logo: "https://www.yoursite.com/logo.png", // TODO: replace with actual logo URL
  sameAs: [
    "https://www.facebook.com/yourpage",
    "https://www.linkedin.com/company/yourpage",
    // add/remove as needed
  ],
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+1-555-555-5555", // TODO
    contactType: "customer service",
  },
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-XGQ2P9EDJ7"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-XGQ2P9EDJ7');
            `,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ToastProvider>
            <DeskstopNavigationMenu />
            {children}
            <Footer />
          </ToastProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}