// apps/web/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider, useToast } from "@repo/ui";

export const metadata: Metadata = {
  title: "Dinel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body><ToastProvider>{children}</ToastProvider></body>
    </html>
  );
}
