// apps/web/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider, useToast } from "@repo/ui";
import AccessGuard from "@/components/AccessGuard";

export const metadata: Metadata = {
  title: "Staffing Outsource",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <AccessGuard />
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}